version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: reservation_app:latest
    container_name: reservation_app
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=reservation_db
      - DB_USER=root
      - DB_PASS=
      - MONGO_URL=mongodb://mongo:27017/reservation_mongo
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - mongo
    volumes:
      - ./:/usr/src/app
       - /usr/src/app/node_modules
    command: npm run dev

  mysql:
    image: mysql:8.0
    container_name: reservation_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: reservation_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    container_name: reservation_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
